graphql:
  spqr:
    gui:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photo
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    username:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    open-in-view: true
  mail:
    host: smtp.sendgrid.net
    port: 587
    username:
    password:
    protocol: smtp
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernamte.type: trace