graphql:
  spqr:
    gui:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photo
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: secure
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  mail:
    host: smtp.sendgrid.net
    port: 465
    username: apikey
    password: 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
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernamte.type: trace